In [49]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [50]:
df=pd.read_csv("daatset.csv")

In [51]:
df

,policy_tenure,age_of_car,age_of_policyholder,population_density,M1_enc,M10_enc,M11_enc,M2_enc,M3_enc,M4_enc,...,seg_B2_enc,seg_C1_enc,seg_C2_enc,seg_utility_enc,make_1_enc,make_2_enc,make_3_enc,make_4_enc,make_5_enc,is_claim
0,0.515874,0.05,0.644231,4990,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,0.672619,0.02,0.375000,27003,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0.841110,0.02,0.384615,4076,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0.900277,0.11,0.432692,21622,0,0,0,1,0,0,...,0,1,0,0,1,0,0,0,0,0
4,0.596403,0.11,0.634615,34738,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58587,0.355089,0.13,0.644231,8794,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
58588,1.199642,0.02,0.519231,7788,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
58589,1.162273,0.05,0.451923,34738,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
58590,1.236307,0.14,0.557692,8794,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
58591,0.124429,0.02,0.442308,8794,0,0,0,0,0,1,...,0,0,1,0,0,0,1,0,0,0

In [52]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [53]:
X

,policy_tenure,age_of_car,age_of_policyholder,population_density,M1_enc,M10_enc,M11_enc,M2_enc,M3_enc,M4_enc,...,seg_B1_enc,seg_B2_enc,seg_C1_enc,seg_C2_enc,seg_utility_enc,make_1_enc,make_2_enc,make_3_enc,make_4_enc,make_5_enc
0,0.515874,0.05,0.644231,4990,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,0.672619,0.02,0.375000,27003,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,0.841110,0.02,0.384615,4076,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,0.900277,0.11,0.432692,21622,0,0,0,1,0,0,...,0,0,1,0,0,1,0,0,0,0
4,0.596403,0.11,0.634615,34738,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58587,0.355089,0.13,0.644231,8794,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
58588,1.199642,0.02,0.519231,7788,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
58589,1.162273,0.05,0.451923,34738,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
58590,1.236307,0.14,0.557692,8794,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
58591,0.124429,0.02,0.442308,8794,0,0,0,0,0,1,...,0,0,0,1,0,0,0,1,0,0

In [54]:
y

0        0
1        0
2        0
3        0
4        0
        ..
58587    0
58588    0
58589    0
58590    0
58591    0
Name: is_claim, Length: 58592, dtype: int64

In [55]:
c=0
for i in y:
    if i==1:
        c=c+1

print(c)

3748

In [39]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, accuracy_score, confusion_matrix
from sklearn.linear_model import LogisticRegression

In [40]:
from sklearn.datasets import make_classification
from sklearn import svm

In [41]:
X_train, X_test,y_train, y_test = train_test_split(X,y,test_size=0.25)

In [42]:
model = svm.SVC(kernel = 'rbf',class_weight={0:0.5,1:7.8})
model.fit(X_train, y_train)

SVC(class_weight={0: 0.5, 1: 7.8})

In [43]:
y_pred = model.predict(X_test)
conf_matrix_l=confusion_matrix(y_test,y_pred)
print(conf_matrix_l)

[[  897 12811]
 [   31   909]]

In [44]:
accuracy_score(y_test,y_pred)

0.12329328235936647

In [45]:
y_prediected=y_pred

In [46]:
for i in range(len(y_pred)):
    if y_pred[i]==0:
        y_pred[i]=1
    else:
        y_pred[i]=0

In [47]:
accuracy_score(y_test,y_pred)

0.8767067176406336

In [48]:
f1_score(y_test,y_pred) # average rate of precision n recall

0.033190578158458245